#!/usr/bin/env python3
"""Install nudge on this machine.

    python3 install.py install
    python3 install.py status
    python3 install.py uninstall

Nothing in the repo records where the repo lives. `install` resolves that here,
at install time, and bakes it into three generated artifacts:

    ~/.local/bin/nudge              shim -> this clone's nudge.py
    ~/.local/bin/nudge-daemon       shim -> this clone's nudge_daemon.py
    ~/Library/LaunchAgents/com.nudge.daemon.plist
    ~/.claude/skills/nudge          symlink -> this clone's skill

So shipping to another machine is `git clone` then `python3 install.py install`,
and moving a clone is the same command run again from its new home.
"""

import argparse
import os
import plistlib
import shutil
import subprocess
import sys

import store

LABEL = "com.nudge.daemon"
AGENT_DIR = os.path.expanduser("~/Library/LaunchAgents")
PLIST = os.path.join(AGENT_DIR, LABEL + ".plist")
BIN = os.path.expanduser("~/.local/bin")
SKILL_LINK = os.path.expanduser("~/.claude/skills/nudge")
HERE = os.path.dirname(os.path.abspath(__file__))

# Every generated shim carries this, so uninstall can tell a shim it wrote from
# an unrelated `nudge` someone else put on the PATH.
MARKER = "# generated by nudge install.py"

SHIMS = {"nudge": "nudge.py", "nudge-daemon": "nudge_daemon.py"}


def shim_body(python, script):
    return "#!/bin/sh\n%s -- re-run it to repoint, do not edit\nexec %s %s \"$@\"\n" % (
        MARKER, _quote(python), _quote(script))


def _quote(path):
    return "'%s'" % path.replace("'", "'\\''")


def shim_path(name):
    return os.path.join(BIN, name)


def is_ours(path):
    """True if `path` is a shim this installer generated."""
    try:
        with open(path) as f:
            return MARKER in f.read(len(MARKER) + 200)
    except (OSError, UnicodeDecodeError):
        return False


def daemon_env(env=None, which=None):
    """The nudge settings to bake into the plist.

    A launchd agent inherits nothing from the shell that installed it, so a
    `NUDGE_TICK`, `NUDGE_HOME` or `NUDGE_SOUND` exported in a terminal would
    otherwise reach the CLI and not the daemon -- the daemon would sweep a different queue, or at a
    different interval, than the one the user thinks they configured. Whatever is
    set at install time is captured here; changing it means re-installing.
    """
    env = os.environ if env is None else env
    settings = {k: env[k] for k in ("NUDGE_TICK", "NUDGE_HOME", "NUDGE_SOUND")
                if env.get(k) is not None and env[k] != ""}
    notifier = env.get("NUDGE_NOTIFIER") or (which or shutil.which)("terminal-notifier")
    if notifier:
        settings["NUDGE_NOTIFIER"] = notifier
    return settings


def plist_body(python=None, here=None, home=None, env=None, which_binary=None):
    """The LaunchAgent. Points at the shim, so a moved clone needs one re-install.

    RunAtLoad starts the daemon at login and KeepAlive restarts it if it dies --
    together they are what lets a scheduled notification outlive the session that
    scheduled it.
    """
    home = store.HOME if home is None else home
    settings = daemon_env(env, which=which_binary)
    body = {
        "Label": LABEL,
        "ProgramArguments": [shim_path("nudge-daemon")],
        "RunAtLoad": True,
        "KeepAlive": True,
        "WorkingDirectory": HERE if here is None else here,
        "StandardOutPath": os.path.join(home, "daemon.log"),
        "StandardErrorPath": os.path.join(home, "daemon.err"),
        "ProcessType": "Background",
    }
    if settings:
        body["EnvironmentVariables"] = settings
    return body


def _domain():
    return "gui/%d" % os.getuid()


def _launchctl(*args):
    return subprocess.run(["launchctl", *args], capture_output=True, text=True)


def is_loaded():
    return _launchctl("print", "%s/%s" % (_domain(), LABEL)).returncode == 0


def _describe(print_output):
    """Pull pid and state out of `launchctl print`.

    Matching on a bare "pid =" substring would hit the `ppid = 1` line first,
    so the key has to be anchored to the start of the stripped line.
    """
    fields = {}
    for line in print_output.splitlines():
        bare = line.strip()
        for key in ("pid", "state"):
            if bare.startswith(key + " ="):
                fields.setdefault(key, bare.split("=", 1)[1].strip())
    state = fields.get("state", "unknown")
    return "pid %s (%s)" % (fields["pid"], state) if "pid" in fields else "no pid (%s)" % state


def write_shims(python=sys.executable, here=HERE, bindir=None):
    """Write both shims, or neither.

    Every destination is checked before anything is written, so refusing one
    foreign command cannot leave the other shim half-installed.
    """
    bindir = BIN if bindir is None else bindir
    targets = {os.path.join(bindir, name): os.path.join(here, script)
               for name, script in SHIMS.items()}
    for path in sorted(targets):
        if os.path.exists(path) and not is_ours(path):
            sys.exit("nudge: %s exists and was not written by nudge -- "
                     "move it aside and re-run" % path)
    os.makedirs(bindir, exist_ok=True)
    for path, script in sorted(targets.items()):
        with open(path, "w") as f:
            f.write(shim_body(python, script))
        os.chmod(path, 0o755)
    return sorted(targets)


def link_skill(link=None, target=None):
    """Point ~/.claude/skills/nudge at this clone's skill.

    Never clobbers: an unrelated directory or a link elsewhere is left in place
    and reported, because that path may be something the user put there.
    """
    link = SKILL_LINK if link is None else link
    target = os.path.join(HERE, ".claude", "skills", "nudge") if target is None else target
    os.makedirs(os.path.dirname(link), exist_ok=True)
    if os.path.islink(link):
        if os.path.realpath(link) == os.path.realpath(target):
            return "already linked"
        os.unlink(link)  # ours to repoint: a link we can see is a link we wrote
        os.symlink(target, link)
        return "repointed"
    if os.path.exists(link):
        return "left alone (not a symlink -- remove it yourself to use the global skill)"
    os.symlink(target, link)
    return "linked"


def cmd_install(args):
    os.makedirs(AGENT_DIR, exist_ok=True)
    os.makedirs(store.HOME, exist_ok=True)
    shims = write_shims()
    if is_loaded():
        _launchctl("bootout", "%s/%s" % (_domain(), LABEL))  # replace cleanly
    with open(PLIST, "wb") as f:
        plistlib.dump(plist_body(), f)
    r = _launchctl("bootstrap", _domain(), PLIST)
    if r.returncode != 0:
        sys.exit("nudge: bootstrap failed: %s" % (r.stderr.strip() or r.returncode))
    print("installed nudge from %s" % HERE)
    for path in shims:
        print("  shim   %s" % path)
    print("  plist  %s" % PLIST)
    print("  skill  %s (%s)" % (SKILL_LINK, link_skill()))
    print("  logs   %s" % store.HOME)
    if BIN not in os.environ.get("PATH", "").split(os.pathsep):
        print("\nnote: %s is not on your PATH, so `nudge` will not resolve.\n"
              "      add it to your shell profile, or call %s directly."
              % (BIN, shim_path("nudge")))


def _is_inside(path, root):
    """True if `path` lies within `root`.

    A plain `startswith` would treat /x/nudge-old as inside /x/nudge and delete
    another clone's skill link, so the comparison is made on path components.
    """
    try:
        return os.path.commonpath([os.path.realpath(path), os.path.realpath(root)]) \
            == os.path.realpath(root)
    except ValueError:  # different drives, or a relative/absolute mix
        return False


def _try_remove(path, removed, failed):
    """Unlink one thing, recording the outcome instead of raising.

    Uninstall never aborts: a plist that will not budge is no reason to leave
    the shims behind.
    """
    try:
        os.unlink(path)
        removed.append(path)
    except OSError as e:
        failed.append((path, e.strerror or str(e)))


def survivors():
    """Everything that should be gone after an uninstall but is not."""
    left = []
    if is_loaded():
        left.append("launchd job %s is still loaded" % LABEL)
    for pid, command in strays():
        left.append("pid %d is still running: %s" % (pid, command))
    if os.path.exists(PLIST):
        left.append("plist %s" % PLIST)
    for name in SHIMS:
        path = shim_path(name)
        if os.path.exists(path) and is_ours(path):
            left.append("shim %s" % path)
    if os.path.islink(SKILL_LINK) and _is_inside(SKILL_LINK, HERE):
        left.append("skill link %s" % SKILL_LINK)
    return left


def cmd_uninstall(args):
    removed, left_alone, failed = [], [], []

    # Stop the daemon before the plist goes, so a refusal here is still
    # recoverable with launchctl -- the job it names would otherwise be gone.
    if is_loaded():
        r = _launchctl("bootout", "%s/%s" % (_domain(), LABEL))
        if r.returncode != 0 and is_loaded():
            failed.append(("launchd job " + LABEL,
                           (r.stderr or "").strip() or "bootout exited %d" % r.returncode))

    if os.path.exists(PLIST):
        _try_remove(PLIST, removed, failed)

    for name in SHIMS:
        path = shim_path(name)
        if not os.path.exists(path):
            continue
        if is_ours(path):
            _try_remove(path, removed, failed)
        else:
            left_alone.append("%s -- not written by nudge" % path)

    if os.path.islink(SKILL_LINK):
        if _is_inside(SKILL_LINK, HERE):
            _try_remove(SKILL_LINK, removed, failed)
        else:
            left_alone.append("%s -- points outside this clone" % SKILL_LINK)

    for path in removed:
        print("removed    %s" % path)
    for item in left_alone:
        print("left       %s" % item)
    for path, why in failed:
        print("FAILED     %s: %s" % (path, why))

    remaining = survivors()
    if remaining:
        print("\nstill present after uninstall:")
        for item in remaining:
            print("  %s" % item)
        print("\nnudge is NOT fully uninstalled. Do not `rm -rf %s` yet --" % store.HOME
              + "\na daemon still running would keep reading it.")
        return 1

    if not removed and not left_alone:
        print("nothing to uninstall")
        return 0

    print("\nuninstalled. State in %s was left alone (rm -rf it to drop the queue)."
          % store.HOME)
    return 0


def plist_program():
    """The program the installed LaunchAgent will exec, or None."""
    try:
        with open(PLIST, "rb") as f:
            return plistlib.load(f)["ProgramArguments"][0]
    except (OSError, KeyError, IndexError, ValueError):
        return None


def problem():
    """Why a scheduled nudge would not fire, or None if it would.

    Checks the program still exists, not just that launchd has the job loaded:
    a clone that moved leaves a loaded job whose shim is gone, which launchd
    reports as healthy right up until it next tries to start it.
    """
    if not os.path.exists(PLIST):
        return "nudge is not installed"
    program = plist_program()
    if not program:
        return "the LaunchAgent plist is unreadable: %s" % PLIST
    if not os.path.exists(program):
        return "the daemon's program is gone (did the clone move?): %s" % program
    if not is_loaded():
        return "the daemon is installed but not loaded"
    return None


def healthy():
    """True when a scheduled nudge would actually fire."""
    return problem() is None


def repair_command():
    """What to run to fix an unhealthy install, naming this clone.

    The clone's path is known at runtime because the shim that invoked us has it
    baked in -- it is never written into a committed file.
    """
    return "%s %s install" % (_quote(sys.executable), _quote(os.path.join(HERE, "install.py")))


DAEMON_NAMES = ("nudge_daemon.py",)


def _process_table():
    """`ps` output as (pid, command) pairs. Empty if ps is unavailable."""
    r = subprocess.run(["ps", "-axo", "pid=,command="], capture_output=True, text=True)
    rows = []
    for line in r.stdout.splitlines():
        pid, _, command = line.strip().partition(" ")
        if pid.isdigit():
            rows.append((int(pid), command.strip()))
    return rows


def strays(managed_pid=None, table=None):
    """Daemon processes launchd is not managing.

    A daemon started by hand outlives the shell that started it and keeps
    sweeping the same queue, so it silently steals jobs from the managed one --
    including firing them at its own interval, which makes `NUDGE_TICK` look
    broken.

    The match is on argv shape -- a python interpreter invoked against a file
    named like the daemon -- not a substring of the whole command. A substring
    test flags any shell or editor that merely mentions the filename.
    """
    found = []
    for pid, command in (_process_table() if table is None else table):
        if pid in (managed_pid, os.getpid()):
            continue
        argv = command.split()
        if not argv or "python" not in os.path.basename(argv[0]).lower():
            continue
        if any(os.path.basename(a) in DAEMON_NAMES for a in argv[1:]):
            found.append((pid, command))
    return found


def status_report():
    lines = []
    managed_pid = None
    if os.path.exists(PLIST):
        r = _launchctl("print", "%s/%s" % (_domain(), LABEL))
        program = plist_program()
        if r.returncode != 0:
            lines.append("daemon  plist present but not loaded")
        elif program and not os.path.exists(program):
            lines.append("daemon  loaded but its program is gone: %s" % program)
        else:
            described = _describe(r.stdout)
            managed_pid = int(described.split()[1]) if described.startswith("pid ") else None
            lines.append("daemon  loaded  %s" % described)
    else:
        lines.append("daemon  not installed")

    for name in SHIMS:
        path = shim_path(name)
        if not os.path.exists(path):
            lines.append("shim    %-13s missing" % name)
        elif is_ours(path):
            lines.append("shim    %-13s -> %s" % (name, _shim_target(path)))
        else:
            lines.append("shim    %-13s exists but was not written by nudge" % name)

    for pid, command in strays(managed_pid):
        lines.append("stray   pid %d is sweeping the same queue outside launchd\n"
                     "        %s\n"
                     "        it will steal jobs and fire them on its own interval --"
                     " `kill %d`" % (pid, command, pid))

    if os.path.islink(SKILL_LINK):
        lines.append("skill   %s -> %s" % (SKILL_LINK, os.path.realpath(SKILL_LINK)))
    elif os.path.exists(SKILL_LINK):
        lines.append("skill   %s exists and is not a symlink" % SKILL_LINK)
    else:
        lines.append("skill   not linked (project-scoped only)")
    return lines


def cmd_status(args):
    """Print the report; exit non-zero with a repair command if nothing would fire."""
    print("\n".join(status_report()))
    why = problem()
    if why:
        print("\n%s -- nothing will fire. to repair:\n  %s" % (why, repair_command()))
        return 1
    return 0


def _shim_target(path):
    """The script a generated shim execs, for status output."""
    with open(path) as f:
        for line in f:
            if line.startswith("exec "):
                return line.split("'")[-2] if "'" in line else line[5:].strip()
    return "?"


def build_parser():
    p = argparse.ArgumentParser(prog="install", description=__doc__.splitlines()[0])
    sub = p.add_subparsers(dest="cmd", required=True)
    for name, fn, help_ in [
        ("install", cmd_install, "write shims, the LaunchAgent and the skill link"),
        ("uninstall", cmd_uninstall, "remove everything install wrote, keeping state"),
        ("status", cmd_status, "show the daemon, the shims and the skill link"),
    ]:
        s = sub.add_parser(name, help=help_)
        s.set_defaults(func=fn)
    return p


if __name__ == "__main__":
    args = build_parser().parse_args()
    # Subcommands return an exit code; uninstall uses it to say "something survived",
    # so `install.py uninstall && rm -rf ~/.nudge` cannot delete a live daemon's queue.
    sys.exit(args.func(args) or 0)
